### ISSUE TITLE
Failed to stage on ms-windows

### ISSUE THREAD

**Issue by ralesi** [syohex/emacs-git-gutter#100]
I am failing to stage on my windows machine.  When navigating through hunks, the only successful staged hunks are new lines.  And changes or deleted lines result in the error: Failed stating this hunk.  The popup and prompt show the correct changes that I intend to stage.  I have tried git-gutter+ and staging works, but it seems like the internals between the two versions are pretty different at this point.   So I don't know where to look at next.

**Comment by syohex** [comment]
Thanks for reporting issue. I don't have Windows machine. So I'll  check this issue next week.

**Comment by ralesi** [comment]
Let me know if there is any testing you need me to perform.   I just thought about increasing the verbosity,  but I dont know if that will help solve the issue.

**Comment by syohex** [comment]
I have sent PR #101. I confirmed git-gutter:stage-hunk is successful with that change on my Windows 7.

**Comment by syohex** [comment]
I have merged #101. Please check latest version.

**Comment by ralesi** [comment]
Thanks,  I will try tonight.
