### ISSUE TITLE
Unchanged face not applying?

### ISSUE THREAD

**Issue by ledbettj** [syohex/emacs-git-gutter#107]
I'm trying to get the background face of `git-gutter` to match my `linum` background.  Working great for added, modified, however unchanged doesn't seem to be working:

Given: `(set-face-background 'git-gutter:unchanged   "red")`, I still see the default frame background color there.

![screen shot 2016-01-08 at 11 30 06 am](https://cloud.githubusercontent.com/assets/805358/12203171/867bc8d8-b5fb-11e5-81e1-7223ea766d5e.png)

Am I using the wrong face or something here?  I also tried setting the unchanged character to `"  " ` and setting the background/foreground with no luck.

**Comment by syohex** [comment]
Thanks for reporting issue. I have fixed this issue at #109. Please update and try again.
