### ISSUE TITLE
Problem with show-paren-mode

### ISSUE THREAD

**Issue by xuchunyang** [syohex/emacs-git-gutter#114]
git-gutter seems to inherit show-paren-mode's face under the following situation:

![screen shot 2016-01-25 at 12 55 00](https://cloud.githubusercontent.com/assets/4550353/12542843/5d44271a-c363-11e5-99f9-827fa72c3ec6.png)

**Comment by syohex** [comment]
Thanks for reporting issue. Could you test latest version ? I suppose this issue fixed by #115.

**Comment by xuchunyang** [comment]
It works fine now, thanks for your work!
