### ISSUE TITLE
Text Moves to the Right with linum-mode

### ISSUE THREAD

**Issue by osxi** [syohex/emacs-git-gutter#116]
On GNU Emacs 25.1.50.1, with linum-mode enabled, I'm experiencing behavior where the text movies right as as I navigate up/down/left/right within a buffer.

It only happens when the file is modified and saved (and a status symbol is displayed in the gutter). If I disable linum-mode (which hides the gutter) or disable git-gutter-mode, the text doesn't move right as I navigate.

I first noticed this a few weeks ago on a fresh Gentoo box with GNU Emacs 25.x but it wasn't happening on my Mac, which had an early HEAD installation of GNU Emacs 25.x. Today, I installed the latest HEAD on my Mac and now the same thing is happening.

Is this a known issue and do you have any suggestions for debugging?

init.el: https://github.com/osxi/emacs-dotfiles/blob/master/init.el

Note: On Linux and OS X, I use Emacs in the terminal, not the GUI. On Linux, I start Emacs with ZSH inside of i3. On Mac, I run Emacs with ZSH inside of tmux. I've ensured that I'm running the latest version at the time of writing this issue (20160126.1947 from MELPA).

**Comment by syohex** [comment]
Could you add `git-gutter:linum-setup` and retry ? 

```patch
diff --git a/init.el b/init.el
index 123eb2a..083950f 100644
--- a/init.el
+++ b/init.el
@@ -42,6 +42,7 @@
 (global-undo-tree-mode t)
 (global-linum-mode t)
 (global-git-gutter-mode t)
+(git-gutter:linum-setup)
 (electric-pair-mode t)
 (electric-indent-mode t)
 (global-auto-revert-mode t)
```

**Comment by syohex** [comment]
However it is difficult that git-gutter works with linum-mode. I recommend you to use [diff-hl](https://github.com/dgutov/diff-hl) or git-gutter-fringe if you want to use linum-mode with such extention.

**Comment by osxi** [comment]
Yeah it took a lot of guesswork to get the two playing nicely together, which I've been able to forget about until recently. However it looks like the problem went away without any config changes so it's probably something to do with running Emacs from master.

I'm going to close this for now and only re-open if I have the specific repro steps.

**Comment by osxi** [comment]
It's worth mentioning also that I've tried using git-gutter-fringe as per your README but had no luck getting it working like I want. git-gutter works great though after some tweaking.

**Comment by naclander** [comment]
FYI, this is still an issue for me as of today using the emacs master branch.
