### ISSUE TITLE
feature-request (?): highlighting of truncated lines

### ISSUE THREAD

**Issue by ErkiDerLoony** [syohex/emacs-git-gutter#121]
Hi, I was wondering if it is possible to also get margin highlights for truncated lines (M-x toggle-truncate-lines)? Currently only the first line is marked in the margin and subsequent lines get no highlight. The same happens for visual-line-mode which soft-breaks long lines.

**Comment by syohex** [comment]
Thanks for suggestion. I have merged #122. However it is slow for large buffer. I'll try to improve it.
