### ISSUE TITLE
Use less defsubst or allow custom plugins

### ISSUE THREAD

**Issue by habnabit** [syohex/emacs-git-gutter#132]
If I want to add my own backend, there's no extension hooks, so I have to `advice-add` on `git-gutter:vcs-check-function` and `git-gutter:start-diff-process1`. Unfortunately, since these are `defsubst` instead of `defun`, they get inlined during compilation. This means I have to either recompile the `.elc` file only after doing the `advice-add` (and after every code change) or not load `git-gutter` from `.elc` at all.

I'm not very familiar with elisp idioms at all, so I can't make any suggestions for how to change the code structure other than "use `defun` instead of `defsubst`". That would be the simplest change that solves my problem, but there might be an easier way to add hooks to simplify others making new backends.

**Comment by syohex** [comment]
How about #134 ? BTW git-gutter:start-diff-process1 is defined by `defun`.

**Comment by habnabit** [comment]
👍 looks good. Also oops my mistake; I knew multiple functions needed to change, but it's the two you changed. I can't check at this exact moment if this change works but I can't imagine why it wouldn't.

**Comment by syohex** [comment]
I have Merged #134.
