### ISSUE TITLE
drop git-gutter:toggle from sample configuration

### ISSUE THREAD

**Issue by marczz** [syohex/emacs-git-gutter#133]
The sample configuration should be:

    (global-set-key (kbd "C-x C-g") 'git-gutter-mode)

as git-gutter:toggle is obsolete.

**Comment by syohex** [comment]
Thanks. I have removed it.

**Comment by marczz** [comment]
Ok, but it is still useful to replace it with:

    (global-set-key (kbd "C-x C-g") 'git-gutter-mode)

to allow manual gutter refresh, by ex when you have committed changes.

**Comment by syohex** [comment]
I suppose `git-gutter` command is useful for such purpose. And I update soon.

**Comment by syohex** [comment]
Updated
