### ISSUE TITLE
git-gutter-mode slowly leaks hg processes if pager is enabled

### ISSUE THREAD

**Issue by durin42** [syohex/emacs-git-gutter#136]
If the Mercurial pager extension is enabled, `git-gutter-mode` slowly leaks `hg` processes (along the lines of `hg diff -U0 $FILE` for me. It's silly to even run the pager anyway, so ideally that'd be avoided. The easy workaround is to make sure the environment variable `HGPLAIN` is set to `1` when running `hg`, which will prevent various things like pager (and color, etc) from interfering with tooling like `git-gutter-mode`.

(For users encountering this bug if it's not still fixed: you can `M-x customize` the variable `git-gutter:mercurial-diff-option` to `"--pager=never"` to work around this as long as you've got the pager extension enabled.)

**Comment by syohex** [comment]
Thanks for reporting issue. I have fixed at #137. Please check latest version.

**Comment by durin42** [comment]
That fix is wrong. You need to set `HGPLAIN=1` in the environment when invoking hg. What you've done breaks all hg users that don't have the pager extension enabled (the default configuration does not provide a `--pager` flag anywhere.)

**Comment by syohex** [comment]
Sorry. I have merged #138.
