### ISSUE TITLE
Quit the hunk popup window with q

### ISSUE THREAD

**Issue by cmellwig** [syohex/emacs-git-gutter#142]
The fix from https://github.com/syohex/emacs-git-gutter/issues/33 doesn't seem to work anymore. I can't close the hunk popup by pressing q (Updated to newest version today).

**Comment by syohex** [comment]
I cannot reproduce. Could you tell me how to reproduce this issue in more detail ? and Please check whether view-mode is enabled in popup-buffer.

**Comment by cmellwig** [comment]
I call git-gutter:popup-hunk. If I switch to the diff buffer, I can't close it via q. view-mode is enabled for the diff buffer. Am I missing something obvious?

**Comment by syohex** [comment]
Which command is assigned `q` in popup buffer ? You can check it by `M-x describe-key` and type `q`

**Comment by cmellwig** [comment]
I see the problem, it's bound to evil-record-macro. Any idea how quit (view-quit?) can take precedence?

**Comment by syohex** [comment]
```
(defun my/view-mode-hook ()
  (define-key evil-normal-state-local-map "q" #'View-quit))

(add-hook 'view-mode-hook #'my/view-mode-hook)
```

I don't use evil and don't understand it well :-(

**Comment by cmellwig** [comment]
Works like a charm, thank you very much!

**Comment by syohex** [comment]
You are welcome
