### ISSUE TITLE
Option to diff against specified commit

### ISSUE THREAD

**Issue by jokem59** [syohex/emacs-git-gutter#164]
It would be nice if there was an option to diff against a specific commit (e.g. diff off of the commit that a branch was forked from).  I'd imagine that this setting would be applied globally if set.

It would make tracking all changes a little easier if one tends to use many small commits vs one large commit.

**Comment by runejuhl** [comment]
There's the function `git-gutter:set-start-revision`:

~~~
git-gutter:set-start-revision is an interactive compiled Lisp function in
‘git-gutter.el’.

(git-gutter:set-start-revision START-REV)

Set start revision. If ‘start-rev’ is nil or empty string then reset
start revision.
~~~

**Comment by jokem59** [comment]
Thanks - this is great =)
