### ISSUE TITLE
Is it possible to display the changes on the fly without saving the file?

### ISSUE THREAD

**Issue by chenglou** [syohex/emacs-git-gutter#79]
Sublime Text does this and it's pretty sweet.

**Comment by syohex** [comment]
Sorry such feature is not implemented yet.
I want to implement this in the future.

**Comment by syohex** [comment]
I implemented this feature experimentally.
If diff information is updated if `git-gutter:update-interval` is larger than 0(Default value is 0).

```lisp
(custom-set-variables
 '(git-gutter:update-interval 2))
```

Here is screencast of this.

![git-gutter-live-update](https://cloud.githubusercontent.com/assets/554281/6711689/e435963e-cdcb-11e4-8f9e-d87e01a72914.gif)

Please report me if you have suggestions or issues.

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

> I implemented this feature experimentally.
> If diff information is updated if git-gutter:update-interval is larger than 0(Default value is 0).
>
> (custom-set-variables
>  '(git-gutter:update-interval 2))

(customize-set-variable
 'git-gutter:update-interval 2)

is even simpler.

> Please report me if you have suggestions or issues.

Seems it works great, very nice thanks.

- Why the timer is not enabled directly in git-gutter-mode ?
  Actually we need global-git-gutter-mode to enable this.

- Maybe global-git-gutter should be renamed to git-gutter-global-mode ?

- When live update is enabled margin in not reset to 0 when there is no
  change, one have to (setq git-gutter:hide-gutter t) to enable this.
  perhaps it should be the default ?

Otherwise cool, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by syohex** [comment]
> (customize-set-variable 'git-gutter:update-interval 2) is even simpler.

Thanks for information.

> - Why the timer is not enabled directly in git-gutter-mode ? Actually we need global-git-gutter-mode to enable this.

Thanks for suggestion. I'll fix it later.

> - Maybe global-git-gutter should be renamed to git-gutter-global-mode ?

Minor global mode name usually starts with `global-` such as `global-company-mode`,
`global-font-lock-mode`, `global-flycheck-mode` etc.

> - When live update is enabled margin in not reset to 0 when there is no change, one have to (setq git-gutter:hide-gutter t) to enable this. perhaps it should be the default ?

I'll check it.

**Comment by syohex** [comment]
> - When live update is enabled margin in not reset to 0 when there is no change, one have to (setq git-gutter:hide-gutter t) to enable this. perhaps it should be the default ?

Mergin is reset to 0 where there are no changes. Do I misunderstand ?

![git-gutter-hide-gutter](https://cloud.githubusercontent.com/assets/554281/6768233/ec795162-d0a2-11e4-895a-abac2585092f.gif)

Would you tell me how to reproduce your issue, if you have problems ?

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

>       + When live update is enabled margin in not reset to 0 when there is no change, one have to (setq git-gutter:hide-gutter t) to enable this. perhaps it should be
>         the default ?
>
> Mergin is reset to 0 where there are no changes.

Only if git-gutter:hide-gutter is non--nil here.

> git-gutt

If must set git-gutter:hide-gutter to non--nil to have the margin reset
to 0 (i.e to have the same behavior as in your animation). 
Actually git-gutter:hide-gutter default value is nil, I was just
suggesting to make non--nil the default.

IOW there is no issue here, only asking for a default setting.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by syohex** [comment]
> If must set git-gutter:hide-gutter to non--nil to have the margin reset to 0 (i.e to have the same behavior as in your animation). Actually git-gutter:hide-gutter default value is nil, I was just suggesting to make non--nil the default. IOW there is no issue here, only asking for a default setting.

Thanks, I understand. But I think that its default value is nil rather than non-nil.

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

> Thanks, I understand. But I think that its default value is nil rather than non-nil.

Exactly, what I suggest is making its default value non--nil.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
