### ISSUE TITLE
Is staging from region a likely future feature?

### ISSUE THREAD

**Issue by whitty** [syohex/emacs-git-gutter#91]
Selectively staging lines by region/selection is a very useful for some workflows.  Is this feature planned or every likely to be developed here?

I'm aware there is another project with this feature, but this one seems to be better supported/tested (eg on TRAMP) and more widely used.

**Comment by syohex** [comment]
> Is this feature planned or every likely to be developed here?

No.

[magit](https://github.com/magit/magit/) provides such feature.
