### ISSUE TITLE
Breaks emacs after file is moved

### ISSUE THREAD

**Issue by expez** [syohex/emacs-git-gutter#94]
Trying to reproduce a bug in a refactoring which moves source files around, I got into this unfortunate situation: 

```
Debugger entered--Lisp error: (file-error "Setting current directory" "no such file or directory" "/home/expez/git/test/src/clj/test/core/")
  call-process("git" nil t nil "rev-parse" "--is-inside-work-tree")
  apply(call-process "git" nil t nil ("rev-parse" "--is-inside-work-tree"))
  process-file("git" nil t nil "rev-parse" "--is-inside-work-tree")
  apply(process-file "git" nil t nil ("rev-parse" "--is-inside-work-tree"))
  git-gutter:in-git-repository-p()
  git-gutter()
```

The directory has been renamed and I can't kill the buffer which is now no longer associated with a file nor visit another buffer.  I just keep getting this `file-error`.  

I now have to kill my emacs instance, loosing all kinds of wonderful state :p

**Comment by syohex** [comment]
Hmm, I cannot reproduce this issue. I would like to know how to reproduce this issue in more detail.

**Comment by expez** [comment]
If I create a dir with some file in emacs,  delete the dir on the commandline, and then call `git-gutter` I see the `file-error` like above, but I can still close that buffer just fine.

I'll re-open if I see this again and can report better reproduction steps.

Sorry about the noise.
