### ISSUE TITLE
Feature request: don't ask for yes-or-no for stage/revert/... operations

### ISSUE THREAD

**Issue by 4DA** [syohex/emacs-git-gutter#95]
For example i wish i could call *git-gutter:revert-hunk* function without being asked yes or no question.

Thanks.

**Comment by syohex** [comment]
I think it is not good. How about following configuration if it is pain to type `yes` or `no` for you ? You can type only `y` or `n` with following configuration.

```
(defalias 'yes-or-no-p 'y-or-n-p)
```

**Comment by 4DA** [comment]
Thanks for advice!

I agree it is not good as a default behavior, i mean a customizable
variable (off by default) that would remove those questions.

If i make a patch will you consider it?

On Wed, Sep 2, 2015 at 5:13 AM, Syohei YOSHIDA <notifications@github.com>
wrote:

> I think it is not good. How about following configuration if it is pain to
> type yes or no for you ? You can type only y or n with following
> configuration.
>
> (defalias 'yes-or-no-p 'y-or-n-p)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syohex/emacs-git-gutter/issues/95#issuecomment-136914986>
> .
>



-- 
With best regards,
Dmitry

**Comment by syohex** [comment]
I see. I will do this tomorrow.

**Comment by syohex** [comment]
Please upgrade latest version and add following configuration in you init.el.

```lisp
(setq git-gutter:ask-p nil)
```

**Comment by 4DA** [comment]
That's very cool. Thanks a lot.

On Thu, Sep 3, 2015 at 10:23 AM, Syohei YOSHIDA <notifications@github.com>
wrote:

> Please upgrade latest version and add following configuration in you
> init.el.
>
> (setq git-gutter:ask-p nil)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syohex/emacs-git-gutter/issues/95#issuecomment-137358826>
> .
>



-- 
With best regards,
Dmitry
